spring:
  application:
    name: micro-service-collector
  security:
    user:
      name: user
      password: Admin@123
server:
  port: 9023
  servlet:
    context-path: /
  ssl:
    enabled: true
    key-store: classpath:key/website_a.jks
    key-password: Admin@1234
    key-store-type: JKS
    key-store-password: Admin@123